name: flutter_application_inz
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6

  cupertino_icons: ^1.0.6
  cookie_jar: ^4.0.8
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3
  dio: ^5.7.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/clipboard.png
    - images/user.png
    - images/register.png

  # fonts:
  #   - family: Inspiration
